### ISSUE TITLE
[BUG] Error response from daemon: network pg-ext not found

### ISSUE THREAD

**Issue by gregorwolf** [Azure-Samples/app-service-javascript-sap-cap-quickstart#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What type of issue are you facing

bug report

### Describe the bug

When I ran `docker-compose -f pg.yml up -d` I've got:

```
Error response from daemon: network pg-ext not found
```

### Expected Behavior

The docker images for postgresql and adminer should start

### Additional context

I only was able to solve it my commenting the networks part in the pg.yml

**Comment by MartinPankraz** [comment]
Seems like we need to address non-GitHub Codespace environments differently. Participants of the DSAG TechXChange using the Codespace had no issues.

Could you confirm your execution environement @gregorwolf?

**Comment by gregorwolf** [comment]
I'm trying to work directly on my Mac with Docker Desktop.

**Comment by ulkeba** [comment]
Hey @gregorwolf!
Thank you so much for bringing this up. We were able to simplify the setup and remove the dependency of the external network; may I kindly ask you to pull the most recent changes and try again?

**Comment by gregorwolf** [comment]
Thank you @ulkeba for the improvement.
